[package]
name = "hello_world_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.0", features = ["derive"] }
indicatif = {version = "*", features = ["rayon"]}
env_logger = "0.9.0"
log = "0.4"
clap = { version = "3.0.5", features = ["derive"] }